### ISSUE TITLE
Error: No active provider set. Please select a provider for this project

### ISSUE THREAD

**Issue by shaneholloman** [jahwag/ClaudeSync#74] opened 2024-09-22 11:27 UTC
### Operating System

windows 11

### Python Version

3.10.14

### ClaudeSync Version

0.6.1

### Installation Type

New

### Configuration

```powershell
  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync config ls
{
  "claude_api_url": "https://api.claude.ai/api",
  "compression_algorithm": "none",
  "file_categories": {
    "all_files": {
      "description": "All files not ignored",
      "patterns": [
        "*"
      ]
    },
    "all_source_code": {
      "description": "All source code files",
      "patterns": [
        "*.java",
        "*.py",
        "*.js",
        "*.ts",
        "*.c",
        "*.cpp",
        "*.h",
        "*.hpp",
        "*.go",
        "*.rs"
      ]
    },
    "build_config": {
      "description": "Build configuration files",
      "patterns": [
        "**/pom.xml",
        "**/build.gradle",
        "**/package.json",
        "**/setup.py",
        "**/Cargo.toml",
        "**/go.mod",
        "**/pyproject.toml",
        "**/requirements.txt",
        "**/*.tf",
        "**/*.yaml",
        "**/*.yml",
        "**/*.properties"
      ]
    },
    "production_code": {
      "description": "Production source code",
      "patterns": [
        "**/src/**/*.java",
        "**/*.py",
        "**/*.js",
        "**/*.ts",
        "**/*.vue"
      ]
    },
    "test_code": {
      "description": "Test source code",
      "patterns": [
        "**/test/**/*.java",
        "**/tests/**/*.py",
        "**/test_*.py",
        "**/*Test.java"
      ]
    },
    "uberproject_java": {
      "description": "Uberproject Java + Javascript",
      "patterns": [
        "**/src/**/*.java",
        "**/*.py",
        "**/*.js",
        "**/*.ts",
        "**/*.vue",
        "**/pom.xml",
        "**/build.gradle",
        "**/package.json",
        "**/setup.py",
        "**/Cargo.toml",
        "**/go.mod",
        "**/pyproject.toml",
        "**/requirements.txt",
        "**/*.tf",
        "**/*.yaml",
        "**/*.yml",
        "**/*.properties"
      ]
    }
  },
  "log_level": "INFO",
  "max_file_size": 32768,
  "prune_remote_files": true,
  "submodule_detect_filenames": [
    "pom.xml",
    "build.gradle",
    "package.json",
    "setup.py",
    "Cargo.toml",
    "go.mod"
  ],
  "two_way_sync": false,
  "upload_delay": 0.5
}
  claudesync 3.10.14  shane @ moa ❯ ~ ❯
```
 

### Steps to Reproduce

steps:

```powershell
  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync auth login
Choose provider (claude.ai) [claude.ai]: claude.ai
A session key is required to call: https://api.claude.ai/api
To obtain your session key, please follow these steps:
1. Open your web browser and go to https://claude.ai
2. Log in to your Claude account if you haven't already
3. Once logged in, open your browser's developer tools:
   - Chrome/Edge: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Firefox: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Safari: Enable developer tools in Preferences > Advanced, then press Cmd+Option+I
4. In the developer tools, go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)
5. In the left sidebar, expand 'Cookies' and select 'https://claude.ai'
6. Locate the cookie named 'sessionKey' and copy its value. Ensure that the value is not URL-encoded.
Please enter your sessionKey:
Please enter the expires time for the sessionKey (optional) [Tue, 22 Oct 2024 11:19:41 UTC]:
Received a 403 Forbidden error.
Failed to retrieve organizations. Please enter a valid sessionKey.
Please enter your sessionKey:
Please enter the expires time for the sessionKey (optional) [Tue, 22 Oct 2024 11:19:55 UTC]:
Successfully authenticated with claude.ai. Session key stored globally.
  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync project create
Enter a title for your new project [shane]: sync-test
Enter the project description [Project created with ClaudeSync]:
Enter the absolute path to your local project directory [C:\Users\shane]: C:\Users\shane\Dropbox\shane\ai\sync
Pick the provider to use for this project (claude.ai) [claude.ai]: claude.ai
Project 'sync-test' (uuid: 6865e2e9-e3ff-46c0-9d44-02ee4c0e22b1) has been created successfully.

Project setup complete. You can now start syncing files with this project. URL: https://claude.ai/project/6865e2e9-e3ff-46c0-9d44-02ee4c0e22b1
  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync push
Error: No active provider set. Please select a provider for this project.
```

### Description

  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync push
Error: No active provider set. Please select a provider for this project.

### Logs

```shell
where are logs saved to in Windows 11?
```

**Comment by jahwag** [comment] 2024-09-26 16:19
It looks like your current working directory is set to C:\Users\shane. However, you’re trying to create the project in C:\Users\shane\Dropbox\shane\ai\sync.

To resolve the issue, you need to change your working directory to C:\Users\shane\Dropbox\shane\ai\sync before running the claudesync push command.

Since this is expected behavior based on your setup, I’ll be closing the issue as it appears to be a user-handling error.

**Comment by shaneholloman** [comment] 2024-09-28 09:15
```powershell
  shane @ moa ❯ sync  ❯ conda activate claudesync
  claudesync 3.10.14  shane @ moa ❯ sync ❯ claudesync push
Error: No active provider set. Please select a provider for this project.
  claudesync 3.10.14  shane @ moa ❯ sync ❯ pwd

Path
----
C:\Users\shane\Dropbox\shane\ai\sync

  claudesync 3.10.14  shane @ moa ❯ sync ❯ cd
  claudesync 3.10.14  shane @ moa ❯ ~ ❯ pwd

Path
----
C:\Users\shane

  claudesync 3.10.14  shane @ moa ❯ ~ ❯ claudesync push
Error: No active provider set. Please select a provider for this project.
  claudesync 3.10.14  shane @ moa ❯ ~ ❯
 ```

**Comment by jahwag** [comment] 2024-09-29 16:00
@shaneholloman can please share the location of your project .claudesync directory

**Comment by beeekind** [comment] 2024-10-03 15:41
I was able to solve this issue by creating a new project with claudesync: `claudesync project create`

**Comment by 26tajeen** [comment] 2024-10-11 14:02
Exact same issue here @jahwag 

macbookpro:~ 26tja$ **claudesync project create**
Enter a title for your new project [26tja]: **SMTP2**
Enter the project description [Project created with ClaudeSync]: **SMTP**
Enter the absolute path to your local project directory [/Users/26tja]: **/Users/26tja/Downloads/smtp-addon-docker-main**
Pick the provider to use for this project (claude.ai) [claude.ai]: **claude.ai**
Project 'SMTP2' (uuid: ffac0be7-bd64-4f46-be52-caae6e117c09) has been created successfully.

Project setup complete. You can now start syncing files with this project. URL: https://claude.ai/project/ffac0be7-bd64-4f46-be52-caae6e117c09
macbookpro:~ 26tja$ **claudesync push**
Error: No active provider set. Please select a provider for this project.
macbookpro:~ 26tja$

**Comment by 26tajeen** [comment] 2024-10-11 15:15
don't think that's it - it seems to be an issue if the cookie expiry date is not explicitly provided on mac - I re-authed and gave it an explicity expiry (rather than using the default suggestion) and that fixed it

**Comment by jahwag** [comment] 2024-10-11 15:59
@26tajeen  
You're misunderstanding. You created the project in /Users/26tja/Downloads/smtp-addon-docker-main, so you need to change your working directory to that before running claudesync push. You did not do that as evidenced by "~ 26tja":
`macbookpro:~ 26tja$ claudesync push
`

**Comment by 26tajeen** [comment] 2024-10-11 18:13
so the correct error message for being in the wrong directory is:
  "No active provider set. Please select a provider for this project."  ??

It's your project, so maybe it is?

**Comment by jahwag** [comment] 2024-10-11 19:02
affirmative, humans are more inventive than there are error messages)

**Comment by 26tajeen** [comment] 2024-10-13 18:36
Proof I was right on Friday :-) 

![Screenshot 2024-10-13 at 19 31 09](https://github.com/user-attachments/assets/e51d3e98-24b5-4555-96ce-65825c00aef2)

Same command issued from the same directory only works if the default option is **not** used and a provider is explicitly chosen

**Comment by ParisMolver** [comment] 2024-10-17 09:28
I too had this issue and fixed it by changing directory from "C:\Users\PcName" to "C:\Users\PcName\Documents". When I ls the projects it shows up.

However now it hangs and doesn't proceed on push.

**Comment by n0vedad** [comment] 2024-10-23 14:42
related error here, created a project directly at the Claude website, switched to the directory with the files I want to sync and need to do `claudesync organization set` and `claudesync project set` twice before I'm able to do `claudesync push`

otherwise I get "No active provider set" too

**Comment by jahwag** [comment] 2024-10-23 16:03
To push to a claude.ai project, you must have once set the destination
organization and project via:

claudesync organization set
claudesync project set

OR,

claudesync project create

This will create a hidden .claudesync directory in your working directory
with the specified claude.ai destination. Sub-directories will be
considered part of this project when issuing commands.

There is also the possibility to define submodules, in order to reduce
context window size when working in larger projects. This is not
(well-)documented, but can be inferred from the command line options and
inspection of claudesync.local.json. There are a specific subset of project
files eg package.json that will be considered as constituting a submodule.

Hope that clears up any outstanding questions.

Probably should get around to releasing more helpful error messages
sometime.To push to a claude.ai project, you must have once set the
destination organization and project via: claudesync organization set
claudesync project set OR, claudesync project create This will create a
hidden .claudesync directory in your working directory with the specified
destination. Sub-directories will be considered part of this project. There
is also the possibility to define sub-modules, in order to reduce context
window. This is not (well-)documented but can be inferred from the command
line options and inspection of claudesync.local.json. Hope that clears up
any outstanding questions. Probably should get around to releasing more
helpful error messages.

**Comment by 26tajeen** [comment] 2024-10-23 17:19
There’s definitely a bug around having to create the project twice sometimes (using identical commands) before it will allow you to do a `Claudesync push`

**Closed** 2024-10-23 21:37 UTC
Labels: invalid
