### ISSUE TITLE
Received a 403 Forbidden error. Your session key might be invalid. Please try logging out and logging in again....

### ISSUE THREAD

**Issue by sintetico82** [jahwag/ClaudeSync#42] opened 2024-08-07 16:10 UTC
**Describe the bug**

Unable to login, i am tring put session key and the expiration date (that I have to convert in this format reading the code "%a, %d %b %Y %H:%M:%S %Z") but I am unable to login.

log:

Please enter your sessionKey: sk-ant-sid01-xxx
Please enter the expires time for the sessionKey [Fri, 06 Sep 2024 16:05:52 UTC]: Thu, 06 Sep 2024 15:57:41 UTC
2024-08-07 18:06:00,628 - DEBUG - Making GET request to https://api.claude.ai/api/organizations
2024-08-07 18:06:00,629 - DEBUG - Headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0', 'Origin': 'https://claude.ai', 'Referer': 'https://claude.ai/projects', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, zstd', 'Accept-Language': 'en-US,en;q=0.5', 'anthropic-client-sha': 'unknown', 'anthropic-client-version': 'unknown', 'Connection': 'keep-alive', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-origin'}
2024-08-07 18:06:00,629 - DEBUG - Cookies: {'sessionKey': 'sk-ant-sid01-xxx', 'CH-prefers-color-scheme': 'dark', 'anthropic-consent-preferences': '{"analytics":true,"marketing":true}'}
2024-08-07 18:06:00,718 - DEBUG - Response status code: 403
2024-08-07 18:06:00,718 - DEBUG - Response headers: {'Date': 'Wed, 07 Aug 2024 16:06:00 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cf_bm=jpJuL97L72xH1OMbJvti3egvAuiY3m5hfICZWWK1m7g-1723046760-1.0.1.1-6VCqgVrjlheYNwbj1WMq3gIeUGyUWQIwT7ZO0B9nkErsKqXef2auKMEioSP3M5ZG9.XIhHrmUaqDb.mSTv2TJw; path=/; expires=Wed, 07-Aug-24 16:36:00 GMT; domain=.claude.ai; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '8af882ee5e88374e-MXP', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400'}
2024-08-07 18:06:00,719 - DEBUG - Response content: {"error":{"message":"We are unable to serve your request","type":"permission_error"}}...
2024-08-07 18:06:00,719 - ERROR - Received a 403 Forbidden error. Your session key might be invalid. Please try logging out and logging in again. If the issue persists, you can try using the claude.ai-curl provider as a workaround:

**Comment by jahwag** [comment] 2024-08-07 16:23
Have you tried the claude.ai-curl provider? https://github.com/jahwag/ClaudeSync/wiki/Troubleshooting#1-authentication-failures

**Comment by sintetico82** [comment] 2024-08-07 16:28
Yes, same error...

claudesync api login claude.ai-curl
To obtain your session key, please follow these steps:
1. Open your web browser and go to https://claude.ai
2. Log in to your Claude account if you haven't already
3. Once logged in, open your browser's developer tools:
   - Chrome/Edge: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Firefox: Press F12 or Ctrl+Shift+I (Cmd+Option+I on Mac)
   - Safari: Enable developer tools in Preferences > Advanced, then press Cmd+Option+I
4. In the developer tools, go to the 'Application' tab (Chrome/Edge) or 'Storage' tab (Firefox)
5. In the left sidebar, expand 'Cookies' and select 'https://claude.ai'
6. Locate the cookie named 'sessionKey' and copy its value. Ensure that the value is not URL-encoded.
Please enter your sessionKey: sk-ant-sid01-xxx
Please enter the expires time for the sessionKey [Fri, 06 Sep 2024 16:26:38 UTC]: Thu, 06 Sep 2024 15:57:41 UTC
2024-08-07 18:26:50,243 - DEBUG - Executing command: curl https://api.claude.ai/api/organizations --compressed -s -S -w %{http_code} -H User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0 -H Cookie: sessionKey=sk-ant-sid01-xxx -H Content-Type: application/json
2024-08-07 18:26:50,335 - ERROR - cURL command failed with return code 43. stdout: 000, stderr: curl: (43) A libcurl function was given a bad argument
. Request headers: ['-H', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0', '-H', 'Cookie: sessionKey=sk-ant-sid01-xxx', '-H', 'Content-Type: application/json']
cURL command failed with return code 43. stdout: 000, stderr: curl: (43) A libcurl function was given a bad argument
. Request headers: ['-H', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0', '-H', 'Cookie: sessionKey=sk-ant-sid01-xxx', '-H', 'Content-Type: application/json']
Failed to retrieve organizations. Please enter a valid sessionKey.

**Comment by sintetico82** [comment] 2024-08-07 16:46
Ok I try to use WLS with Ubutu 22.04.2 LTS and login now work but on CURL mode

I think something related to CURL on my windows machine

**Comment by jahwag** [comment] 2024-08-07 17:24
Closing as duplicate of #24.

**Closed by jahwag** 2024-08-07 17:24 UTC
Labels: bug
